name: epi2melabs-wf-human-sv
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.8.*
    - gcc_linux-64
    - make
    - aplanat >=0.3.5
    - pysam
    - nanoplot
    - fastcat
    - lra
    - seqtk
    - cutesv
    - samtools
    - bedtools
    - bcftools
    - vcftools
    - vcflib
    - mosdepth
    - NanoPlot==1.38.0
    - pip:
        - catfishq
        - Truvari
        